# GitHub Labeler
# https://github.com/marketplace/actions/github-labeler

# default
- name: ğŸ”¨ breaking changes
  color: F2DE92
  description: ê¸°ì¡´ ê¸°ëŠ¥ì— ì˜í–¥ì„ ì£¼ëŠ” ìˆ˜ì •
- name: ğŸ¨ design
  color: 1B9C99
  description: ì™¸ë¶€ íˆ´ì—ì„œ ë””ìì¸ ì‘ì—… (Figma, Sketch, etc)
- name: ğŸ“ docs
  color: 0075ca
  description: ë¬¸ì„œí™” ë° ë¬¸ì„œ ìˆ˜ì •
- name: ğŸ’¡ etc
  color: bfd4f2
  description: ê¸°íƒ€ ì‘ì—… ìˆ˜í–‰
- name: ğŸ› fix bug
  color: 93D7A2
  description: ë²„ê·¸ ìˆ˜ì •
- name: âœ¨ new feature
  color: D5A302
  description: ê¸°ì¡´ ê¸°ëŠ¥ì— ì˜í–¥ì„ ì£¼ì§€ ì•ŠëŠ” ê¸°ëŠ¥ ì¶”ê°€
