filters:
  # PULL_REQUEST_TEMPLATE.md
  - label: ğŸ› fix bug
    regexs:
      - /^- \[(X|x)\] fix\b/m
    events: [pull_request]
    targets: [comment]
  - label: ğŸ“ docs
    regexs:
      - /^- \[(X|x)\] docs\b/m
    events: [pull_request]
    targets: [comment]
  - label: âœ¨ new feature
    regexs:
      - /^- \[(X|x)\] feat\b/m
    events: [pull_request]
    targets: [comment]
  - label: ğŸ¨ design
    regexs:
      - /^- \[(X|x)\] design\b/m
    events: [pull_request]
    targets: [comment]
